baseurl = "https://naoimporta.com"
languageCode = "pt-br"
title = "Não Importa"
theme = "naoimporta"
paginate = 10

PygmentsCodeFences = true
PygmentsStyle = "trac"
PygmentsUseClasses = false

[Permalinks]
    artigo = "artigo/:slug"

[Taxonomies]
    tag = "tags"
    categories = "categories"
    projetos = "projetos"

[Params]
    languagecode = "pt-BR"
    author = "Fábio Luciano"
    twitter = "https://twitter.com/fabioluciano"
    github = "https://github.com/fabioluciano"
    stackoverflow = "https://stackoverflow.com/users/2971028/fabioluciano"
    facebook = "https://www.facebook.com/fabioluciano"
    linkedin = "https://www.linkedin.com/in/fabioluciano"
    email =  "fabio@naoimporta.com"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Arquivos"
    url = "/artigo"
    weight = 2

[[menu.main]]
    name = "Projetos"
    url = "/projeto"
    weight = 4

[params.strings]
    date_format = '02-01-2006'
