languageCode = "pt-br"
builddrafts = false
baseUrl = "http://naoimporta.com/"
canonifyurls = true
title = "Pixyll"
author = "fabioluciano"
theme = "hugo-theme-pixyll"

[indexes]
  category = "categories"
  tag = "tags"

[params]
  search_engine = true
  google_analytics_id = "UA-24614996-1"
  twitter_username = "fabioluciano"
  disqus_shortname = "noimporta"
  paginate = true
